services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - '9900:9000'
      - '9901:9001'
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=tomcat
      - MINIO_ROOT_PASSWORD=tomcatisroot
    command: server /data --console-address ":9001"