from .config_patch import add_remote_config
from .remote_coco_dataset import register_remote_coco_instances,load_remote_coco_json,load_remote_coco_json_fast
from .remote_coco_mapper import RemoteCOCOInstanceDatasetMapper