version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: iamroot
      TZ: 'Asia/Shanghai'
      PGTZ: 'Asia/Shanghai'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432